version: '3.6'

volumes:
  local_mongodb_data: {}

services:
  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo-${PROJECT_NAME}
    tty: true
    ports: ["${MONGO_PORT}:27017"]
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"   
    volumes: 
      # - ./data:/data/db
      - local_mongodb_data:/data/db 
  mongo-exprees:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-admin-${PROJECT_NAME}
    ports: ["8081:${MONGO_EXPRESS_PORT}"]
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:${MONGO_PORT}/
    depends_on:
      - mongo

